import {
  ADMISSION_AND_LOCK_EXEMPT,
  allowAnyDeviceSessionless,
  DEPLOY_APP_COMMAND_DESCRIPTOR,
  HOST_PLATFORM_EXECUTION,
  NO_PLATFORM_EXECUTION,
  ownerFilesEnabled,
  REQUEST_EXECUTION_EXEMPT,
  resolveDeferredProviderAppCatalogLeaseAdmissionExemption,
  resolvePlainCloseLeaseAdmissionExemption,
  type RawCommandDescriptor,
} from '../descriptor-traits.ts';
import {
  readyMaterializeAndDeployAppUse,
  readySendPushNotificationUse,
} from '@agent-device/contracts/app-deployment-runtime-plan';
import {
  closeApplicationRuntimePlanUses,
  openApplicationRuntimePlanUses,
  prepareAppleRunnerRuntimeUse,
} from '@agent-device/contracts/application-lifecycle-runtime-plan';
import { inventoryUse } from '@agent-device/contracts/platform-module';
import {
  appEventRuntimeUse,
  appsRuntimeUse,
  deviceBootRuntimeUses,
  shutdownTargetUse,
  viewportRuntimeUse,
} from '@agent-device/contracts/platform-runtime-operations';
import { DEFAULT_TIMEOUT_POLICY, PREPARE_REQUEST_TIMEOUT_MS } from '../timeout-policy.ts';

/**
 * The management family (`src/commands/management/**`): commands that own a device or an app's
 * lifecycle around a session — inventory, boot, install, open/close, push, artifacts, viewport.
 */
export const MANAGEMENT_COMMAND_DESCRIPTORS = [
  {
    name: 'artifacts',
    deviceClaimPolicy: 'none',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/artifacts.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: false,
    daemon: {
      route: 'lease',
      refFrameEffect: 'preserve',
      ...ADMISSION_AND_LOCK_EXEMPT,
    },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: false,
    platformExecution: NO_PLATFORM_EXECUTION,
  },
  {
    name: 'devices',
    deviceClaimPolicy: 'observe',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/device.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: false,
    daemon: {
      route: 'session',
      refFrameEffect: 'preserve',
      sessionKind: 'inventory',
      lockPolicySelectorOverride: true,
      ...REQUEST_EXECUTION_EXEMPT,
    },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
    platformExecution: { kind: 'inventory', use: inventoryUse },
  },
  {
    name: 'capabilities',
    deviceClaimPolicy: 'observe',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/device.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: false,
    daemon: {
      route: 'session',
      refFrameEffect: 'preserve',
      sessionKind: 'inventory',
      lockPolicySelectorOverride: true,
      preferExplicitDeviceOverExistingSession: true,
      ...REQUEST_EXECUTION_EXEMPT,
    },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
    // R63: `capabilities` executes nothing on a device. It reads one side-effect-free facts
    // inspection and projects each command's own declared uses against it, so it has no platform
    // execution path of its own to migrate — which is what `none` states. It is deliberately last
    // among the command units: it projects the union of every migrated command's facts, so it is
    // only truthful once that surface is complete.
    platformExecution: NO_PLATFORM_EXECUTION,
  },
  {
    name: 'doctor',
    deviceClaimPolicy: 'observe',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/doctor.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: false,
    daemon: {
      route: 'session',
      refFrameEffect: 'preserve',
      sessionKind: 'inventory',
      lockPolicySelectorOverride: true,
      allowSessionlessDefaultDevice: allowAnyDeviceSessionless,
      ...REQUEST_EXECUTION_EXEMPT,
    },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
    platformExecution: HOST_PLATFORM_EXECUTION,
  },
  {
    name: 'apps',
    deviceClaimPolicy: 'observe',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/app.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: false,
    daemon: {
      route: 'session',
      refFrameEffect: 'preserve',
      sessionKind: 'inventory',
      lockPolicySelectorOverride: true,
      preferExplicitDeviceOverExistingSession: true,
      sessionlessLeaseAdmissionExemption: resolveDeferredProviderAppCatalogLeaseAdmissionExemption,
    },
    platformExecution: { kind: 'device-runtime', uses: [appsRuntimeUse] as const },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
  },
  {
    name: 'boot',
    deviceClaimPolicy: 'transient-exclusive',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/device.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: false,
    daemon: {
      route: 'session',
      refFrameEffect: 'may-invalidate',
      sessionKind: 'state',
    },
    platformExecution: { kind: 'device-runtime', uses: deviceBootRuntimeUses },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
  },
  {
    name: 'shutdown',
    deviceClaimPolicy: 'transient-exclusive',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/device.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: false,
    daemon: {
      route: 'session',
      refFrameEffect: 'may-invalidate',
      sessionKind: 'state',
    },
    platformExecution: { kind: 'device-runtime', use: shutdownTargetUse },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
  },
  {
    name: 'install',
    ...DEPLOY_APP_COMMAND_DESCRIPTOR,
  },
  {
    name: 'reinstall',
    ...DEPLOY_APP_COMMAND_DESCRIPTOR,
  },
  {
    name: 'push',
    deviceClaimPolicy: 'transient-exclusive',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/push.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: true,
    recordingEffect: 'mutates-app',
    daemon: { route: 'session', refFrameEffect: 'may-invalidate' },
    platformExecution: { kind: 'device-runtime', use: readySendPushNotificationUse },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
  },
  {
    name: 'trigger-app-event',
    deviceClaimPolicy: 'require-owner',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/push.ts'] as const } : {}),
    catalog: { group: 'public', key: 'triggerAppEvent' },
    frameworkTier: 'extended',
    // R57 retires this command's capability bucket and its `dispatch` leaf together: admission is
    // the owner's `triggerAppEvent` fact, and the only execution is that one bound operation. The
    // event name, payload, and URL template stay daemon policy (ADR 0019 §2 — a facet input names
    // no command, request, or CLI flag), so the owner receives a URL to open.
    recordsSessionAction: true,
    recordingEffect: 'mutates-app',
    daemon: { route: 'session', refFrameEffect: 'may-invalidate' },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
    platformExecution: { kind: 'device-runtime', uses: [appEventRuntimeUse] },
  },
  {
    name: 'open',
    deviceClaimPolicy: 'acquire-session',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/app.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'core',
    recordsSessionAction: true,
    recordingEffect: 'mutates-app',
    daemon: {
      route: 'session',
      refFrameEffect: 'may-invalidate',
      allowSessionlessDefaultDevice: allowAnyDeviceSessionless,
      saveScriptFlagOwner: true,
    },
    // --timeout is a startup budget: it reaches the Simulator boot wait (#2324).
    timeoutPolicy: { ...DEFAULT_TIMEOUT_POLICY, budget: { source: 'flag', envelope: 'margin' } },
    batchable: true,
    platformExecution: { kind: 'device-runtime', uses: openApplicationRuntimePlanUses },
  },
  {
    name: 'prepare',
    deviceClaimPolicy: 'transient-exclusive',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/prepare.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: false,
    daemon: { route: 'session', refFrameEffect: 'preserve' },
    // Runner warm-up builds are the longest fixed envelope; --timeout is the
    // daemon-side boot + runner budget, so the envelope keeps a margin over it.
    timeoutPolicy: {
      budget: { source: 'flag', envelope: 'margin' },
      envelopeMs: PREPARE_REQUEST_TIMEOUT_MS,
      onTimeout: 'reset-daemon',
    },
    batchable: false,
    mcpExposed: false,
    platformExecution: { kind: 'device-runtime', use: prepareAppleRunnerRuntimeUse },
  },
  {
    name: 'close',
    deviceClaimPolicy: 'release-session',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/app.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'core',
    recordsSessionAction: true,
    recordingEffect: 'mutates-app',
    daemon: {
      route: 'session',
      refFrameEffect: 'may-invalidate',
      allowInvalidRecording: true,
      saveScriptFlagOwner: true,
      sessionlessLeaseAdmissionExemption: resolvePlainCloseLeaseAdmissionExemption,
    },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
    platformExecution: { kind: 'device-runtime', uses: closeApplicationRuntimePlanUses },
  },
  {
    name: 'viewport',
    deviceClaimPolicy: 'require-owner',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/viewport.ts'] as const } : {}),
    catalog: { group: 'public' },
    frameworkTier: 'extended',
    recordsSessionAction: true,
    recordingEffect: 'mutates-app',
    daemon: { route: 'generic', refFrameEffect: 'may-invalidate' },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: false,
    platformExecution: { kind: 'device-runtime', uses: [viewportRuntimeUse] },
  },
  {
    name: 'install-from-source',
    deviceClaimPolicy: 'none',
    ...(ownerFilesEnabled ? { ownerFiles: ['src/commands/management/install.ts'] as const } : {}),
    catalog: { group: 'public', key: 'installFromSource' },
    frameworkTier: 'extended',
    recordsSessionAction: true,
    recordingEffect: 'mutates-app',
    platformExecution: { kind: 'device-runtime', use: readyMaterializeAndDeployAppUse },
    timeoutPolicy: DEFAULT_TIMEOUT_POLICY,
    batchable: true,
  },
] as const satisfies readonly RawCommandDescriptor[];
