// The shell vocabulary the terminal resolver reads: which words are launchers whose arguments
// decide what runs, and which are inert. Data, kept out of execution-terminals.ts so that file
// stays a readable account of the resolution itself.

/** A path that names a runnable script file rather than a tool on PATH. */
export const SCRIPT_FILE = /\.(?:[cm]?[jt]s)$|\.sh$/;

/** Shell builtins and inert commands that do no gated work. */
export const IGNORED_COMMANDS = new Set([
  'if',
  'then',
  'else',
  'elif',
  'fi',
  'for',
  'do',
  'done',
  'while',
  'case',
  'esac',
  'set',
  'echo',
  'printf',
  'cd',
  'mkdir',
  'rm',
  'cp',
  'mv',
  'ln',
  'cat',
  'test',
  '[',
  'exit',
  'true',
  'false',
  'export',
  'source',
  '.',
  'sleep',
  'touch',
  'chmod',
  'shift',
  'return',
  'local',
  'unset',
  'read',
  'eval',
  'trap',
  'wait',
  'kill',
  'pwd',
  'ls',
  'find',
  'grep',
  'rg',
  'sed',
  'awk',
  'sort',
  'uniq',
  'head',
  'tail',
  'tr',
  'cut',
  'xargs',
  'tee',
  'curl',
  'git',
  'gh',
  'unzip',
  'zip',
  'tar',
  'defaults',
  'xcrun',
  'adb',
  'brew',
  'sudo',
  'apt-get',
  'java',
  'javac',
  'swift',
  'open',
  'killall',
  'plutil',
  'security',
  'softwareupdate',
  'sw_vers',
]);

/** pnpm's own subcommands — these run the package manager, not a repo script. */
export const PNPM_SUBCOMMANDS = new Set([
  'install',
  'i',
  'add',
  'remove',
  'rm',
  'update',
  'up',
  'audit',
  'why',
  'list',
  'ls',
  'outdated',
  'pack',
  'publish',
  'prune',
  'rebuild',
  'root',
  'bin',
  'store',
  'link',
  'unlink',
  'import',
  'setup',
  'config',
  'env',
  'licenses',
  'patch',
  'dlx',
  'create',
  'deploy',
  'server',
  'start',
  'test',
  'init',
  'fetch',
  'approve-builds',
]);

/** pnpm flags that redirect the invocation into a different package. */

/** pnpm flags that redirect the invocation into a different package. */
export const PNPM_DIR_FLAGS = new Set([
  '--dir',
  '-C',
  '--filter',
  '--workspace-root',
  '-w',
  '-r',
  '--recursive',
]);

/** `-p`/`-e` evaluate inline source; there is no gated work to attribute to a file. */
export const NODE_EVAL_FLAGS = new Set(['-p', '-e', '--eval', '--print']);

/** Flags that select a whole workspace rather than one directory. */
export const PNPM_WORKSPACE_FLAGS = new Set(['--workspace-root', '-w', '-r', '--recursive']);
