export {
  REPLAY_DIVERGENCE_DEFAULT_REF_LIMIT,
  REPLAY_DIVERGENCE_DIGEST_REF_LIMIT,
  REPLAY_DIVERGENCE_LEVEL_BYTE_LIMITS,
  REPLAY_DIVERGENCE_SUGGESTION_LIMIT,
  applyReplayDivergenceLevelCaps,
  boundReplayDivergence,
  createReplayDivergenceSanitizer,
  formatReplayDivergenceReport,
  measureReplayDivergenceBytes,
  sanitizeReplayDivergenceField,
  scrubReplayVarValues,
  truncateUtf8Field,
} from '../replay-divergence.ts';
export type {
  ReplayDivergence,
  ReplayDivergenceCause,
  ReplayDivergenceKind,
  ReplayDivergenceOverflow,
  ReplayDivergenceResume,
  ReplayDivergenceScreen,
  ReplayDivergenceScreenRef,
  ReplayDivergenceStep,
  ReplayDivergenceStepSource,
  ReplayDivergenceSuggestion,
  ReplayDivergenceSuggestionBasis,
  ReplayDivergenceTargetBinding,
  ReplayDivergenceTargetBindingKind,
  ReplayDivergenceTargetCandidate,
  ReplayDivergenceTargetIdentity,
  ReplayRepairHint,
  ReplayVarScrubEntry,
} from '../replay-divergence.ts';
