export {
  coerceExecResult,
  type CommandExecutorOverride,
  type ExecBackgroundOptions,
  type ExecBackgroundResult,
  type ExecDetachedExit,
  execFailureDetails,
  type ExecOptions,
  type ExecResult,
  isExecutablePath,
  requireExecSuccess,
  resolveExecutableOverridePath,
  resolveFileOverridePath,
  runCmd,
  runCmdBackground,
  runCmdDetached,
  runCmdDetachedMonitored,
  runCmdStreaming,
  runCmdSync,
  whichCmd,
  withCommandExecutorOverride,
  withoutCommandExecutorOverride,
} from './internal/exec.ts';
export { shellQuote, shellQuoteIfNeeded } from './internal/shell-quote.ts';
