import {
  buildUiHierarchySnapshot,
  type AndroidUiHierarchy,
} from '../../platforms/android/ui-hierarchy.ts';
import type { RawSnapshotNode } from '../../kernel/snapshot.ts';

/**
 * Reconstructs the `AndroidUiHierarchy` tree `buildUiHierarchySnapshot` expects
 * (see `platforms/android/ui-hierarchy.ts`) from a flat `RawSnapshotNode[]`
 * fixture that carries `index`/`parentIndex` (the shape Android capture
 * fixtures already use throughout the test suite). Only the fields the walker
 * actually reads for its inclusion decisions
 * (`shouldIncludeAndroidNode`/`shouldIncludeStructuralAndroidNode`) are
 * threaded through: `type`, `identifier`, `label`, `value`, `hittable`,
 * `visibleToUser`, `rect`, plus `bundleId` -> `packageName` (echoed back onto
 * the walked output as `bundleId`, which the chrome/divergence classifiers key
 * on). `depth`/`parentIndex` on the tree node itself are vestigial (the walker
 * tracks depth and parent via its own recursion, never `node.depth`), so they
 * are not populated here.
 */
export function rawFixtureToAndroidTree(rawNodes: RawSnapshotNode[]): AndroidUiHierarchy {
  const root: AndroidUiHierarchy = {
    type: null,
    label: null,
    value: null,
    identifier: null,
    packageName: null,
    depth: -1,
    children: [],
  };
  const byIndex = new Map<number, AndroidUiHierarchy>();
  for (const raw of rawNodes) {
    byIndex.set(raw.index, {
      type: raw.type ?? null,
      label: raw.label ?? null,
      value: raw.value ?? null,
      identifier: raw.identifier ?? null,
      packageName: raw.bundleId ?? null,
      rect: raw.rect,
      hittable: raw.hittable,
      visibleToUser: raw.visibleToUser,
      depth: 0,
      children: [],
    });
  }
  for (const raw of rawNodes) {
    const node = byIndex.get(raw.index);
    if (!node) continue;
    const parent = raw.parentIndex !== undefined ? byIndex.get(raw.parentIndex) : undefined;
    (parent ?? root).children.push(node);
  }
  return root;
}

/**
 * Runs a `RawSnapshotNode[]` fixture through the REAL non-raw Android walk
 * (`buildUiHierarchySnapshot(..., { raw: false })`), the same drop+reparent
 * pass a device `snapshot` capture applies before nodes ever reach
 * `collectSettleChromeRefs` / the replay divergence screen builder. Unlabeled,
 * non-hittable, generic-id structural nodes (`shouldIncludeStructuralAndroidNode`)
 * are dropped and their children re-parented upward — so fixtures built this
 * way reproduce production's inclusion decisions exactly, instead of hand-
 * simulating only the `status_bar*`/`navigation_bar*` wrapper removal.
 */
export function walkNonRawAndroidFixture(rawNodes: RawSnapshotNode[]): RawSnapshotNode[] {
  const tree = rawFixtureToAndroidTree(rawNodes);
  return buildUiHierarchySnapshot(tree, undefined, { raw: false }).nodes;
}

/**
 * Real device capture (checkout-form fixture app, Gboard open, status bar
 * visible) archived at `~/.agent-device-bench/replay-runs/android-ime/raw-ime2.json`
 * (#1251). This is the `--raw` tree: `--raw` keeps every structural wrapper
 * node (`status_bar_container`, `status_bar_contents`, ...), unlike a default
 * capture. Shared across the chrome-classification tests
 * (`core/__tests__/snapshot-chrome-android-statusbar.test.ts`) and the replay
 * divergence route test (`daemon/handlers/__tests__/session-replay-divergence.test.ts`)
 * so both exercise the exact same real screen through `walkNonRawAndroidFixture`.
 */
export const ANDROID_IME_CAPTURE_RAW_NODES: RawSnapshotNode[] = [
  { index: 0, type: 'android.widget.FrameLayout', bundleId: 'com.android.systemui' },
  {
    index: 1,
    parentIndex: 0,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/status_bar_launch_animation_container',
  },
  {
    index: 2,
    parentIndex: 0,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/status_bar_container',
  },
  {
    index: 3,
    parentIndex: 2,
    type: 'androidx.compose.ui.platform.ComposeView',
    bundleId: 'com.android.systemui',
  },
  { index: 4, parentIndex: 3, type: 'android.view.View', bundleId: 'com.android.systemui' },
  {
    index: 5,
    parentIndex: 4,
    type: 'androidx.compose.ui.viewinterop.ViewFactoryHolder',
    bundleId: 'com.android.systemui',
  },
  {
    index: 6,
    parentIndex: 5,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/status_bar',
  },
  {
    index: 7,
    parentIndex: 6,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/status_bar_contents',
  },
  {
    index: 8,
    parentIndex: 7,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/status_bar_start_side_container',
  },
  {
    index: 9,
    parentIndex: 8,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/status_bar_start_side_content',
  },
  {
    index: 10,
    parentIndex: 9,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/status_bar_start_side_except_heads_up',
  },
  {
    index: 11,
    parentIndex: 10,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/clock',
    label: '7:03',
  },
  {
    index: 12,
    parentIndex: 10,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/start_side_notif_and_chip_container',
  },
  {
    index: 13,
    parentIndex: 12,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/notification_icon_area',
  },
  {
    index: 14,
    parentIndex: 13,
    type: 'android.view.ViewGroup',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/notificationIcons',
  },
  {
    index: 15,
    parentIndex: 14,
    type: 'android.widget.ImageView',
    bundleId: 'com.android.systemui',
    label: 'Security & privacy notification: ',
  },
  {
    index: 16,
    parentIndex: 7,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/cutout_space_view',
  },
  {
    index: 17,
    parentIndex: 7,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/status_bar_end_side_container',
  },
  {
    index: 18,
    parentIndex: 17,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/status_bar_end_side_content',
  },
  {
    index: 19,
    parentIndex: 18,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/system_icons',
  },
  {
    index: 20,
    parentIndex: 19,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/statusIcons',
  },
  {
    index: 21,
    parentIndex: 20,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/mobile_combo',
    label: 'T-Mobile, signal full.',
  },
  {
    index: 22,
    parentIndex: 21,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/mobile_group',
  },
  {
    index: 23,
    parentIndex: 22,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
  },
  {
    index: 24,
    parentIndex: 23,
    type: 'android.widget.ImageView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/mobile_signal',
  },
  {
    index: 25,
    parentIndex: 20,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/wifi_combo',
  },
  {
    index: 26,
    parentIndex: 25,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/wifi_group',
  },
  {
    index: 27,
    parentIndex: 26,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/wifi_combo',
  },
  {
    index: 28,
    parentIndex: 27,
    type: 'android.widget.ImageView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/wifi_signal',
    label: 'Wifi signal full.',
  },
  {
    index: 29,
    parentIndex: 19,
    type: 'androidx.compose.ui.platform.ComposeView',
    bundleId: 'com.android.systemui',
  },
  { index: 30, parentIndex: 29, type: 'android.view.View', bundleId: 'com.android.systemui' },
  {
    index: 31,
    parentIndex: 30,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/battery',
  },
  {
    index: 32,
    parentIndex: 31,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Battery 100 percent.',
  },
  {
    index: 33,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 34,
    parentIndex: 33,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 35,
    parentIndex: 34,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'android:id/content',
  },
  {
    index: 36,
    parentIndex: 35,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'android:id/parentPanel',
  },
  {
    index: 37,
    parentIndex: 36,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'android:id/inputArea',
  },
  {
    index: 38,
    parentIndex: 37,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 39,
    parentIndex: 38,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 40,
    parentIndex: 39,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 41,
    parentIndex: 40,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/keyboard_holder',
  },
  {
    index: 42,
    parentIndex: 41,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/keyboard_header_view_holder',
  },
  {
    index: 43,
    parentIndex: 42,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 44,
    parentIndex: 43,
    type: 'android.view.ViewGroup',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 45,
    parentIndex: 44,
    type: 'android.view.View',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 46,
    parentIndex: 44,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/key_pos_header_access_points_menu',
    label: 'Open features menu',
  },
  {
    index: 47,
    parentIndex: 46,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 48,
    parentIndex: 47,
    type: 'android.widget.ImageView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 49,
    parentIndex: 44,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 50,
    parentIndex: 49,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 51,
    parentIndex: 50,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/softkey_holder_fixed_candidates',
  },
  {
    index: 52,
    parentIndex: 51,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    label: 'name',
  },
  {
    index: 53,
    parentIndex: 52,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 54,
    parentIndex: 53,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 55,
    parentIndex: 54,
    type: 'android.widget.TextView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
    label: 'name',
  },
  {
    index: 56,
    parentIndex: 53,
    type: 'android.widget.ImageView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 57,
    parentIndex: 51,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    label: 'names',
  },
  {
    index: 58,
    parentIndex: 57,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 59,
    parentIndex: 58,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 60,
    parentIndex: 59,
    type: 'android.widget.TextView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
    label: 'names',
  },
  {
    index: 61,
    parentIndex: 58,
    type: 'android.widget.ImageView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 62,
    parentIndex: 51,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 63,
    parentIndex: 62,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    label: '📛 emoji',
  },
  {
    index: 64,
    parentIndex: 63,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 65,
    parentIndex: 64,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 66,
    parentIndex: 65,
    type: 'android.view.View',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
    label: '📛 emoji',
  },
  {
    index: 67,
    parentIndex: 44,
    type: 'android.speech.SpeechRecognizer.VoiceDictationButton',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/key_pos_header_power_key',
    label: 'Use voice typing',
  },
  {
    index: 68,
    parentIndex: 67,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/host',
  },
  {
    index: 69,
    parentIndex: 68,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 70,
    parentIndex: 69,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 71,
    parentIndex: 69,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 72,
    parentIndex: 69,
    type: 'android.view.View',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 73,
    parentIndex: 69,
    type: 'android.widget.ImageView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 74,
    parentIndex: 41,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 75,
    parentIndex: 74,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 76,
    parentIndex: 75,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 77,
    parentIndex: 76,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/input_area',
  },
  {
    index: 78,
    parentIndex: 77,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 79,
    parentIndex: 78,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/D01',
    label: 'q',
  },
  {
    index: 80,
    parentIndex: 79,
    type: 'android.widget.TextView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
    label: 'q',
  },
  {
    index: 81,
    parentIndex: 79,
    type: 'android.widget.TextView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
    label: '1',
  },
  {
    index: 82,
    parentIndex: 78,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/D02',
    label: 'w',
  },
  {
    index: 109,
    parentIndex: 77,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 110,
    parentIndex: 109,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/C01',
    label: 'a',
  },
  {
    index: 132,
    parentIndex: 77,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 133,
    parentIndex: 132,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/key_pos_shift',
    label: 'Shift',
  },
  {
    index: 149,
    parentIndex: 132,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/key_pos_del',
    label: 'Delete',
  },
  {
    index: 151,
    parentIndex: 76,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/0_resource_name_obfuscated',
  },
  {
    index: 158,
    parentIndex: 151,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/key_pos_space',
    label: 'Space',
  },
  {
    index: 163,
    parentIndex: 151,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'com.google.android.inputmethod.latin:id/key_pos_ime_action',
    label: 'Done',
  },
  {
    index: 169,
    parentIndex: 33,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
  },
  {
    index: 170,
    parentIndex: 169,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'android:id/input_method_navigation_bar_view',
  },
  {
    index: 176,
    parentIndex: 170,
    type: 'android.widget.ImageView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'android:id/input_method_nav_back',
    label: 'Back',
  },
  {
    index: 178,
    parentIndex: 170,
    type: 'android.widget.ImageView',
    bundleId: 'com.google.android.inputmethod.latin',
    identifier: 'android:id/input_method_nav_ime_switcher',
    label: 'Switch input method',
  },
  { index: 180, type: 'android.widget.FrameLayout', bundleId: 'com.callstack.agentdevicelab' },
  {
    index: 181,
    parentIndex: 180,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 182,
    parentIndex: 181,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 183,
    parentIndex: 182,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.callstack.agentdevicelab',
    identifier: 'com.callstack.agentdevicelab:id/action_bar_root',
  },
  {
    index: 184,
    parentIndex: 183,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.callstack.agentdevicelab',
    identifier: 'android:id/content',
  },
  {
    index: 185,
    parentIndex: 184,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 193,
    parentIndex: 185,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 194,
    parentIndex: 193,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 196,
    parentIndex: 193,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 197,
    parentIndex: 196,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 198,
    parentIndex: 197,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 199,
    parentIndex: 198,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 200,
    parentIndex: 199,
    type: 'android.widget.ScrollView',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 201,
    parentIndex: 200,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 202,
    parentIndex: 201,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 203,
    parentIndex: 202,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 204,
    parentIndex: 203,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 205,
    parentIndex: 204,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 206,
    parentIndex: 205,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 207,
    parentIndex: 206,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 208,
    parentIndex: 207,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 210,
    parentIndex: 208,
    type: 'android.widget.ScrollView',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 211,
    parentIndex: 210,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
  },
  {
    index: 212,
    parentIndex: 211,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
    identifier: 'form-title',
  },
  {
    index: 213,
    parentIndex: 211,
    type: 'android.widget.TextView',
    bundleId: 'com.callstack.agentdevicelab',
    label: 'Checkout form',
  },
  {
    index: 220,
    parentIndex: 211,
    type: 'android.widget.TextView',
    bundleId: 'com.callstack.agentdevicelab',
    label: 'Full name',
  },
  {
    index: 221,
    parentIndex: 211,
    type: 'android.widget.EditText',
    bundleId: 'com.callstack.agentdevicelab',
    identifier: 'field-name',
    label: 'review name',
  },
  {
    index: 222,
    parentIndex: 211,
    type: 'android.widget.TextView',
    bundleId: 'com.callstack.agentdevicelab',
    label: 'Email',
  },
  {
    index: 223,
    parentIndex: 211,
    type: 'android.widget.EditText',
    bundleId: 'com.callstack.agentdevicelab',
    identifier: 'field-email',
    label: 'ada@example.com',
  },
  {
    index: 224,
    parentIndex: 211,
    type: 'android.widget.TextView',
    bundleId: 'com.callstack.agentdevicelab',
    label: 'Phone',
  },
  {
    index: 225,
    parentIndex: 211,
    type: 'android.widget.EditText',
    bundleId: 'com.callstack.agentdevicelab',
    identifier: 'field-phone',
    label: '+48 555 010 010',
  },
  {
    index: 226,
    parentIndex: 211,
    type: 'android.view.ViewGroup',
    bundleId: 'com.callstack.agentdevicelab',
    identifier: 'android-ime-capture-fixture',
  },
];

/**
 * Real device capture (emulator-5556, Pixel 9 Pro XL API 37, deskclock in the
 * foreground, `adb shell cmd statusbar expand-settings`) archived at
 * `~/.agent-device-bench/wave3/validation/captures/legE-qsshade-raw-tree.json`
 * (wave-3 leg E). A FULLY expanded quick-settings shade: every node belongs to
 * `com.android.systemui` and the whole surface hangs off one `legacy_window_root`
 * — a SINGLE chrome run — with the status-bar icons (`clock`, `mobile_signal`,
 * `wifi_signal`) sitting inside that same window alongside the 23 hittable
 * `qs_tile_*` targets. That co-tenancy is what makes the run-level chrome rule
 * condemn the tiles, so the shape must come from a real capture rather than
 * hand-written ids. `--raw` keeps the structural wrappers a default capture drops.
 */
export const ANDROID_QS_SHADE_CAPTURE_RAW_NODES: RawSnapshotNode[] = [
  {
    index: 0,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/legacy_window_root',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 1,
    parentIndex: 0,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/light_reveal_scrim',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 2,
    parentIndex: 0,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/scrim_in_front',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 3,
    parentIndex: 0,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/low_light_animation_container',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 4,
    parentIndex: 0,
    type: 'android.view.ViewGroup',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/shared_notification_container',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 5,
    parentIndex: 4,
    type: 'android.widget.ScrollView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/notification_stack_scroller',
    rect: { x: 0, y: 0, width: 1344, height: 2896 },
  },
  {
    index: 6,
    parentIndex: 0,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/notification_panel',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 7,
    parentIndex: 6,
    type: 'android.view.ViewGroup',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/notification_container_parent',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 8,
    parentIndex: 7,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_frame',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 9,
    parentIndex: 8,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 10,
    parentIndex: 9,
    type: 'androidx.compose.ui.platform.ComposeView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/quick_settings_container',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 11,
    parentIndex: 10,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 12,
    parentIndex: 11,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 13,
    parentIndex: 12,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 0, y: 0, width: 1344, height: 2992 },
  },
  {
    index: 14,
    parentIndex: 13,
    type: 'android.widget.ScrollView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/expanded_qs_scroll_view',
    rect: { x: 0, y: 0, width: 1344, height: 2740 },
  },
  {
    index: 15,
    parentIndex: 14,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/quick_settings_panel',
    rect: { x: 0, y: 399, width: 1344, height: 1368 },
  },
  {
    index: 16,
    parentIndex: 15,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/brightness_slider',
    rect: { x: 48, y: 465, width: 1248, height: 156 },
  },
  {
    index: 17,
    parentIndex: 16,
    type: 'android.widget.SeekBar',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/slider',
    label: 'Display brightness',
    value: 'Display brightness',
    hittable: true,
    rect: { x: 48, y: 465, width: 1248, height: 156 },
  },
  {
    index: 18,
    parentIndex: 17,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 1006, y: 465, width: 144, height: 156 },
  },
  {
    index: 19,
    parentIndex: 15,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_pager',
    rect: { x: 48, y: 687, width: 1248, height: 936 },
  },
  {
    index: 20,
    parentIndex: 19,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 48, y: 687, width: 1248, height: 936 },
  },
  {
    index: 21,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 48, y: 687, width: 612, height: 216 },
  },
  {
    index: 22,
    parentIndex: 21,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 48, y: 687, width: 612, height: 216 },
  },
  {
    index: 23,
    parentIndex: 22,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_large',
    hittable: true,
    rect: { x: 48, y: 687, width: 612, height: 216 },
  },
  {
    index: 24,
    parentIndex: 23,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_toggle_target',
    hittable: true,
    rect: { x: 72, y: 711, width: 168, height: 168 },
  },
  {
    index: 25,
    parentIndex: 24,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Wi-Fi,AndroidWifi',
    rect: { x: 72, y: 711, width: 168, height: 168 },
  },
  {
    index: 26,
    parentIndex: 24,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 114, y: 753, width: 84, height: 84 },
  },
  {
    index: 27,
    parentIndex: 24,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 72, y: 711, width: 168, height: 168 },
  },
  {
    index: 28,
    parentIndex: 23,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 258, y: 687, width: 378, height: 216 },
  },
  {
    index: 29,
    parentIndex: 28,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    label: 'Wi-Fi',
    value: 'Wi-Fi',
    rect: { x: 258, y: 750, width: 378, height: 49 },
  },
  {
    index: 30,
    parentIndex: 28,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    label: 'AndroidWifi',
    value: 'AndroidWifi',
    rect: { x: 258, y: 799, width: 378, height: 42 },
  },
  {
    index: 31,
    parentIndex: 23,
    type: 'android.widget.Button',
    bundleId: 'com.android.systemui',
    rect: { x: 48, y: 687, width: 612, height: 216 },
  },
  {
    index: 32,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 684, y: 687, width: 612, height: 216 },
  },
  {
    index: 33,
    parentIndex: 32,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 684, y: 687, width: 612, height: 216 },
  },
  {
    index: 34,
    parentIndex: 33,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_large',
    hittable: true,
    rect: { x: 684, y: 687, width: 612, height: 216 },
  },
  {
    index: 35,
    parentIndex: 34,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_toggle_target',
    hittable: true,
    rect: { x: 708, y: 711, width: 168, height: 168 },
  },
  {
    index: 36,
    parentIndex: 35,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Bluetooth.',
    rect: { x: 708, y: 711, width: 168, height: 168 },
  },
  {
    index: 37,
    parentIndex: 35,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 750, y: 753, width: 84, height: 84 },
  },
  {
    index: 38,
    parentIndex: 35,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 708, y: 711, width: 168, height: 168 },
  },
  {
    index: 39,
    parentIndex: 34,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 894, y: 687, width: 378, height: 216 },
  },
  {
    index: 40,
    parentIndex: 39,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    label: 'Bluetooth',
    value: 'Bluetooth',
    rect: { x: 894, y: 771, width: 378, height: 49 },
  },
  {
    index: 41,
    parentIndex: 34,
    type: 'android.widget.Button',
    bundleId: 'com.android.systemui',
    rect: { x: 684, y: 687, width: 612, height: 216 },
  },
  {
    index: 42,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 48, y: 927, width: 612, height: 216 },
  },
  {
    index: 43,
    parentIndex: 42,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 48, y: 927, width: 612, height: 216 },
  },
  {
    index: 44,
    parentIndex: 43,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_large',
    hittable: true,
    rect: { x: 48, y: 927, width: 612, height: 216 },
  },
  {
    index: 45,
    parentIndex: 44,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_toggle_target',
    hittable: true,
    rect: { x: 72, y: 951, width: 168, height: 168 },
  },
  {
    index: 46,
    parentIndex: 45,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Mobile data',
    rect: { x: 72, y: 951, width: 168, height: 168 },
  },
  {
    index: 47,
    parentIndex: 45,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 114, y: 993, width: 84, height: 84 },
  },
  {
    index: 48,
    parentIndex: 45,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 72, y: 951, width: 168, height: 168 },
  },
  {
    index: 49,
    parentIndex: 44,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 258, y: 927, width: 378, height: 216 },
  },
  {
    index: 50,
    parentIndex: 49,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    label: 'Mobile data',
    value: 'Mobile data',
    rect: { x: 258, y: 990, width: 378, height: 49 },
  },
  {
    index: 51,
    parentIndex: 49,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    label: 'T-Mobile, 5G',
    value: 'T-Mobile, 5G',
    rect: { x: 258, y: 1039, width: 378, height: 42 },
  },
  {
    index: 52,
    parentIndex: 44,
    type: 'android.widget.Button',
    bundleId: 'com.android.systemui',
    rect: { x: 48, y: 927, width: 612, height: 216 },
  },
  {
    index: 53,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 684, y: 927, width: 612, height: 216 },
  },
  {
    index: 54,
    parentIndex: 53,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 684, y: 927, width: 612, height: 216 },
  },
  {
    index: 55,
    parentIndex: 54,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_large',
    hittable: true,
    rect: { x: 684, y: 927, width: 612, height: 216 },
  },
  {
    index: 56,
    parentIndex: 55,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 750, y: 993, width: 84, height: 84 },
  },
  {
    index: 57,
    parentIndex: 55,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 894, y: 927, width: 378, height: 216 },
  },
  {
    index: 58,
    parentIndex: 57,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    label: 'Quick Share',
    value: 'Quick Share',
    rect: { x: 894, y: 1011, width: 378, height: 49 },
  },
  {
    index: 59,
    parentIndex: 55,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 684, y: 927, width: 612, height: 216 },
  },
  {
    index: 60,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 48, y: 1167, width: 612, height: 216 },
  },
  {
    index: 61,
    parentIndex: 60,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 48, y: 1167, width: 612, height: 216 },
  },
  {
    index: 62,
    parentIndex: 61,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_large',
    hittable: true,
    rect: { x: 48, y: 1167, width: 612, height: 216 },
  },
  {
    index: 63,
    parentIndex: 62,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_toggle_target',
    hittable: true,
    rect: { x: 72, y: 1191, width: 168, height: 168 },
  },
  {
    index: 64,
    parentIndex: 63,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Modes. ',
    rect: { x: 72, y: 1191, width: 168, height: 168 },
  },
  {
    index: 65,
    parentIndex: 63,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 114, y: 1233, width: 84, height: 84 },
  },
  {
    index: 66,
    parentIndex: 63,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 72, y: 1191, width: 168, height: 168 },
  },
  {
    index: 67,
    parentIndex: 62,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 258, y: 1167, width: 378, height: 216 },
  },
  {
    index: 68,
    parentIndex: 67,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    label: 'Modes',
    value: 'Modes',
    rect: { x: 258, y: 1251, width: 378, height: 49 },
  },
  {
    index: 69,
    parentIndex: 62,
    type: 'android.widget.Button',
    bundleId: 'com.android.systemui',
    rect: { x: 48, y: 1167, width: 612, height: 216 },
  },
  {
    index: 70,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 684, y: 1167, width: 612, height: 216 },
  },
  {
    index: 71,
    parentIndex: 70,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 684, y: 1167, width: 612, height: 216 },
  },
  {
    index: 72,
    parentIndex: 71,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_large',
    hittable: true,
    rect: { x: 684, y: 1167, width: 612, height: 216 },
  },
  {
    index: 73,
    parentIndex: 72,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 750, y: 1233, width: 84, height: 84 },
  },
  {
    index: 74,
    parentIndex: 72,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 894, y: 1167, width: 366, height: 216 },
  },
  {
    index: 75,
    parentIndex: 74,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    label: 'Wallet',
    value: 'Wallet',
    rect: { x: 894, y: 1230, width: 366, height: 49 },
  },
  {
    index: 76,
    parentIndex: 74,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 894, y: 1279, width: 366, height: 42 },
  },
  {
    index: 77,
    parentIndex: 72,
    type: 'android.widget.Button',
    bundleId: 'com.android.systemui',
    rect: { x: 684, y: 1167, width: 612, height: 216 },
  },
  {
    index: 78,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 48, y: 1407, width: 294, height: 216 },
  },
  {
    index: 79,
    parentIndex: 78,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 48, y: 1407, width: 294, height: 216 },
  },
  {
    index: 80,
    parentIndex: 79,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_small',
    hittable: true,
    rect: { x: 48, y: 1407, width: 294, height: 216 },
  },
  {
    index: 81,
    parentIndex: 80,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Airplane mode',
    rect: { x: 48, y: 1407, width: 294, height: 216 },
  },
  {
    index: 82,
    parentIndex: 80,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 147, y: 1467, width: 96, height: 96 },
  },
  {
    index: 83,
    parentIndex: 80,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 48, y: 1407, width: 294, height: 216 },
  },
  {
    index: 84,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 366, y: 1407, width: 294, height: 216 },
  },
  {
    index: 85,
    parentIndex: 84,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 366, y: 1407, width: 294, height: 216 },
  },
  {
    index: 86,
    parentIndex: 85,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_small',
    hittable: true,
    rect: { x: 366, y: 1407, width: 294, height: 216 },
  },
  {
    index: 87,
    parentIndex: 86,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Auto-rotate screen',
    rect: { x: 366, y: 1407, width: 294, height: 216 },
  },
  {
    index: 88,
    parentIndex: 86,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 465, y: 1467, width: 96, height: 96 },
  },
  {
    index: 89,
    parentIndex: 86,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 366, y: 1407, width: 294, height: 216 },
  },
  {
    index: 90,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 684, y: 1407, width: 294, height: 216 },
  },
  {
    index: 91,
    parentIndex: 90,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 684, y: 1407, width: 294, height: 216 },
  },
  {
    index: 92,
    parentIndex: 91,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_small',
    hittable: true,
    rect: { x: 684, y: 1407, width: 294, height: 216 },
  },
  {
    index: 93,
    parentIndex: 92,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Flashlight',
    rect: { x: 684, y: 1407, width: 294, height: 216 },
  },
  {
    index: 94,
    parentIndex: 92,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 783, y: 1467, width: 96, height: 96 },
  },
  {
    index: 95,
    parentIndex: 92,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 684, y: 1407, width: 294, height: 216 },
  },
  {
    index: 96,
    parentIndex: 20,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 1002, y: 1407, width: 294, height: 216 },
  },
  {
    index: 97,
    parentIndex: 96,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/tile_expandable',
    rect: { x: 1002, y: 1407, width: 294, height: 216 },
  },
  {
    index: 98,
    parentIndex: 97,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_small',
    hittable: true,
    rect: { x: 1002, y: 1407, width: 294, height: 216 },
  },
  {
    index: 99,
    parentIndex: 98,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Battery Saver',
    rect: { x: 1002, y: 1407, width: 294, height: 216 },
  },
  {
    index: 100,
    parentIndex: 98,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_tile_icon',
    rect: { x: 1101, y: 1467, width: 96, height: 96 },
  },
  {
    index: 101,
    parentIndex: 98,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 1002, y: 1407, width: 294, height: 216 },
  },
  {
    index: 102,
    parentIndex: 15,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    hittable: true,
    rect: { x: 600, y: 1623, width: 144, height: 144 },
  },
  {
    index: 103,
    parentIndex: 15,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 1152, y: 1623, width: 144, height: 144 },
  },
  {
    index: 104,
    parentIndex: 103,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_edit_mode_button',
    hittable: true,
    rect: { x: 1152, y: 1623, width: 144, height: 144 },
  },
  {
    index: 105,
    parentIndex: 104,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Edit order of Quick Settings.',
    rect: { x: 1188, y: 1659, width: 72, height: 72 },
  },
  {
    index: 106,
    parentIndex: 104,
    type: 'android.widget.Button',
    bundleId: 'com.android.systemui',
    rect: { x: 1164, y: 1635, width: 120, height: 120 },
  },
  {
    index: 107,
    parentIndex: 13,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/qs_footer_actions',
    rect: { x: 0, y: 2740, width: 1344, height: 180 },
  },
  {
    index: 108,
    parentIndex: 107,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 36, y: 2764, width: 1272, height: 144 },
  },
  {
    index: 109,
    parentIndex: 108,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/multi_user_switch',
    hittable: true,
    rect: { x: 876, y: 2764, width: 144, height: 144 },
  },
  {
    index: 110,
    parentIndex: 109,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Signed in as Owner',
    rect: { x: 918, y: 2806, width: 60, height: 60 },
  },
  {
    index: 111,
    parentIndex: 108,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/settings_button_container',
    hittable: true,
    rect: { x: 1020, y: 2764, width: 144, height: 144 },
  },
  {
    index: 112,
    parentIndex: 111,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Open settings.',
    rect: { x: 1062, y: 2806, width: 60, height: 60 },
  },
  {
    index: 113,
    parentIndex: 108,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/pm_lite',
    hittable: true,
    rect: { x: 1164, y: 2764, width: 144, height: 144 },
  },
  {
    index: 114,
    parentIndex: 113,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Power menu',
    rect: { x: 1206, y: 2806, width: 60, height: 60 },
  },
  {
    index: 115,
    parentIndex: 7,
    type: 'android.view.ViewGroup',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/split_shade_status_bar',
    hittable: true,
    rect: { x: 0, y: 0, width: 1344, height: 384 },
  },
  {
    index: 116,
    parentIndex: 115,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/carrier_group',
    rect: { x: 48, y: 156, width: 1248, height: 156 },
  },
  {
    index: 117,
    parentIndex: 116,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/carrier1',
    hittable: true,
    rect: { x: 1121, y: 156, width: 175, height: 156 },
  },
  {
    index: 118,
    parentIndex: 117,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/carrier_combo',
    rect: { x: 1121, y: 205, width: 175, height: 57 },
  },
  {
    index: 119,
    parentIndex: 118,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/mobile_carrier_text',
    label: 'T-Mobile',
    value: 'T-Mobile',
    rect: { x: 1121, y: 205, width: 163, height: 57 },
  },
  {
    index: 120,
    parentIndex: 115,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/clock',
    label: '9:56',
    value: '9:56',
    hittable: true,
    rect: { x: 48, y: 34, width: 339, height: 350 },
  },
  {
    index: 121,
    parentIndex: 115,
    type: 'android.widget.TextView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/date',
    label: 'Fri, Jul 17',
    value: 'Fri, Jul 17',
    rect: { x: 48, y: 312, width: 183, height: 72 },
  },
  {
    index: 122,
    parentIndex: 115,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/shade_header_system_icons',
    rect: { x: 231, y: 312, width: 1065, height: 72 },
  },
  {
    index: 123,
    parentIndex: 122,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/hover_system_icons_container',
    rect: { x: 1061, y: 312, width: 235, height: 72 },
  },
  {
    index: 124,
    parentIndex: 123,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/statusIcons',
    rect: { x: 1061, y: 315, width: 144, height: 66 },
  },
  {
    index: 125,
    parentIndex: 124,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/mobile_combo',
    label: 'T-Mobile, three bars.',
    rect: { x: 1061, y: 315, width: 69, height: 66 },
  },
  {
    index: 126,
    parentIndex: 125,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/mobile_group',
    rect: { x: 1070, y: 315, width: 51, height: 66 },
  },
  {
    index: 127,
    parentIndex: 126,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    rect: { x: 1070, y: 330, width: 51, height: 36 },
  },
  {
    index: 128,
    parentIndex: 127,
    type: 'android.widget.ImageView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/mobile_signal',
    rect: { x: 1070, y: 330, width: 51, height: 36 },
  },
  {
    index: 129,
    parentIndex: 124,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/wifi_combo',
    rect: { x: 1130, y: 315, width: 66, height: 66 },
  },
  {
    index: 130,
    parentIndex: 129,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/wifi_group',
    rect: { x: 1139, y: 315, width: 48, height: 66 },
  },
  {
    index: 131,
    parentIndex: 130,
    type: 'android.widget.FrameLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/wifi_combo',
    rect: { x: 1139, y: 330, width: 48, height: 36 },
  },
  {
    index: 132,
    parentIndex: 131,
    type: 'android.widget.ImageView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/wifi_signal',
    label: 'Wifi signal full.',
    rect: { x: 1139, y: 330, width: 48, height: 36 },
  },
  {
    index: 133,
    parentIndex: 123,
    type: 'androidx.compose.ui.platform.ComposeView',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/battery_meter_composable_view',
    rect: { x: 1205, y: 328, width: 91, height: 39 },
  },
  {
    index: 134,
    parentIndex: 133,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 1205, y: 328, width: 91, height: 39 },
  },
  {
    index: 135,
    parentIndex: 134,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    rect: { x: 1205, y: 328, width: 91, height: 39 },
  },
  {
    index: 136,
    parentIndex: 135,
    type: 'android.view.View',
    bundleId: 'com.android.systemui',
    label: 'Battery charging, 100 percent.',
    rect: { x: 1205, y: 328, width: 72, height: 39 },
  },
  {
    index: 137,
    parentIndex: 0,
    type: 'android.widget.LinearLayout',
    bundleId: 'com.android.systemui',
    identifier: 'com.android.systemui:id/keyguard_message_area_container',
    rect: { x: 0, y: 156, width: 1344, height: 2836 },
  },
];
