const COMMAND_OWNER_FILES: Readonly<Record<string, readonly string[]>> = {
  alert: ['src/commands/capture/alert.ts'],
  appstate: ['src/commands/system/index.ts'],
  'app-switcher': ['src/commands/system/index.ts'],
  apps: ['src/commands/management/app.ts'],
  artifacts: ['src/commands/management/artifacts.ts'],
  audio: ['src/commands/observability/index.ts'],
  back: ['src/commands/system/index.ts'],
  batch: ['src/commands/batch/index.ts'],
  boot: ['src/commands/management/device.ts'],
  capabilities: ['src/commands/management/device.ts'],
  click: ['src/commands/interaction/index.ts'],
  clipboard: ['src/commands/system/index.ts'],
  close: ['src/commands/management/app.ts'],
  debug: ['src/commands/debugging/index.ts'],
  devices: ['src/commands/management/device.ts'],
  diff: ['src/commands/capture/diff.ts'],
  doctor: ['src/commands/management/doctor.ts'],
  events: ['src/commands/observability/index.ts'],
  fill: ['src/commands/interaction/index.ts'],
  find: ['src/commands/interaction/index.ts'],
  focus: ['src/commands/interaction/index.ts'],
  get: ['src/commands/interaction/index.ts'],
  gesture: ['src/commands/interaction/index.ts'],
  home: ['src/commands/system/index.ts'],
  install: ['src/commands/management/install.ts'],
  'install-from-source': ['src/commands/management/install.ts'],
  is: ['src/commands/interaction/index.ts'],
  keyboard: ['src/commands/system/index.ts'],
  logs: ['src/commands/observability/index.ts'],
  longpress: ['src/commands/interaction/index.ts'],
  metro: ['src/commands/metro/index.ts'],
  network: ['src/commands/observability/index.ts'],
  open: ['src/commands/management/app.ts'],
  perf: ['src/commands/perf/index.ts'],
  prepare: ['src/commands/management/prepare.ts'],
  press: ['src/commands/interaction/index.ts'],
  push: ['src/commands/management/push.ts'],
  'react-native': ['src/commands/react-native/index.ts'],
  record: ['src/commands/recording/index.ts'],
  reinstall: ['src/commands/management/install.ts'],
  replay: ['src/commands/replay/index.ts'],
  rotate: ['src/commands/system/index.ts'],
  screenshot: ['src/commands/capture/screenshot.ts'],
  scroll: ['src/commands/interaction/index.ts'],
  session: ['src/commands/management/session.ts'],
  settings: ['src/commands/capture/settings.ts'],
  shutdown: ['src/commands/management/device.ts'],
  snapshot: ['src/commands/capture/snapshot.ts'],
  swipe: ['src/commands/interaction/index.ts'],
  test: ['src/commands/replay/index.ts'],
  trace: ['src/commands/recording/index.ts'],
  'trigger-app-event': ['src/commands/management/push.ts'],
  type: ['src/commands/interaction/index.ts'],
  'tv-remote': ['src/commands/system/index.ts'],
  viewport: ['src/commands/management/viewport.ts'],
  wait: ['src/commands/capture/wait.ts'],
};

export function commandOwnerFiles(command: string): string[] {
  return [...(COMMAND_OWNER_FILES[command] ?? [])];
}
