import type { RuntimeOperationKey } from '@agent-device/contracts/platform-runtime';
import type { PlatformRuntimeOperations } from '@agent-device/contracts/platform-runtime-operations';

/**
 * What one bound runtime operation does to the device when its send returns. `mutates`: the app or
 * device changed, so a resend may repeat an app-visible action. `repeatable`: a resend repeats no
 * app-visible action — reads, idempotent readiness and preparation, and host-side recorder, log,
 * probe, and profiler controls whose repeat the device refuses or ignores.
 */
type RuntimeOperationEffect = 'mutates' | 'repeatable';

/** Every bound operation's effect; the request binding records each `mutates` send it returns. */
export const RUNTIME_OPERATION_EFFECTS: Readonly<
  Record<RuntimeOperationKey<PlatformRuntimeOperations>, RuntimeOperationEffect>
> = Object.freeze({
  acceptAlert: 'mutates',
  actionButton: 'mutates',
  appLogCleanup: 'repeatable',
  appLogDoctor: 'repeatable',
  appLogInspect: 'repeatable',
  appLogReattach: 'repeatable',
  appLogStart: 'repeatable',
  appState: 'repeatable',
  appSwitcher: 'mutates',
  applyRuntimeHints: 'mutates',
  audioProbeCleanup: 'repeatable',
  audioProbeQuery: 'repeatable',
  audioProbeReattach: 'repeatable',
  audioProbeStart: 'repeatable',
  awaitAlert: 'repeatable',
  back: 'mutates',
  bootTarget: 'mutates',
  bootTargetHeadless: 'mutates',
  captureScreenshot: 'repeatable',
  captureSnapshot: 'repeatable',
  captureSnapshotWithCustomActions: 'repeatable',
  captureSnapshotWithoutActiveApp: 'repeatable',
  clearRuntimeHints: 'mutates',
  closeApplication: 'mutates',
  configureProviderPortReverse: 'repeatable',
  deployApp: 'mutates',
  deployMaterializedApp: 'mutates',
  dismissAlert: 'mutates',
  ensureReady: 'repeatable',
  fillPoint: 'mutates',
  fillRef: 'mutates',
  finalizeApplicationClose: 'mutates',
  findText: 'repeatable',
  focusPoint: 'mutates',
  gestureViewport: 'repeatable',
  home: 'mutates',
  hoverPoint: 'mutates',
  hoverRef: 'mutates',
  keyboardDismiss: 'mutates',
  keyboardEnter: 'mutates',
  keyboardStatus: 'repeatable',
  listApps: 'repeatable',
  longPressPoint: 'mutates',
  materializeAppSource: 'repeatable',
  networkDump: 'repeatable',
  openApplication: 'mutates',
  perfFrames: 'repeatable',
  perfMemorySample: 'repeatable',
  perfMemorySnapshot: 'repeatable',
  perfNativeCaptureCleanup: 'repeatable',
  perfNativeCaptureReattach: 'repeatable',
  perfNativeCaptureStart: 'repeatable',
  perfProfileReport: 'repeatable',
  performDirectionalFlingPlan: 'mutates',
  performGesturePlan: 'mutates',
  performMultiTouchGesturePlan: 'mutates',
  performTargetAuthoredDrag: 'mutates',
  prepareAppleRunner: 'repeatable',
  prepareApplicationOpen: 'repeatable',
  readAlert: 'repeatable',
  readClipboard: 'repeatable',
  readSetting: 'repeatable',
  readTextAtPoint: 'repeatable',
  resolveOpenTarget: 'repeatable',
  screenRecordingCleanup: 'repeatable',
  screenRecordingReattach: 'repeatable',
  screenRecordingStart: 'repeatable',
  scrollDirection: 'mutates',
  sendPushNotification: 'mutates',
  setFoldPose: 'mutates',
  setOrientation: 'mutates',
  setSetting: 'mutates',
  setViewport: 'mutates',
  shutdownTarget: 'mutates',
  tapElementSelector: 'mutates',
  tapPoint: 'mutates',
  tapRef: 'mutates',
  triggerAppEvent: 'mutates',
  tvRemote: 'mutates',
  typeText: 'mutates',
  writeClipboard: 'mutates',
});
