import AgentDeviceSnapshotPresentation

typealias RawAXNode = AgentDeviceSnapshotPresentation.RawAXNode
typealias CaptureHint = AgentDeviceSnapshotPresentation.CaptureHint
typealias SnapshotAcquisition = AgentDeviceSnapshotPresentation.SnapshotAcquisition
typealias SnapshotPresentationNode = AgentDeviceSnapshotPresentation.SnapshotPresentationNode
typealias SnapshotGeometry = AgentDeviceSnapshotPresentation.SnapshotGeometry
typealias SnapshotVisibilityFold = AgentDeviceSnapshotPresentation.SnapshotVisibilityFold
typealias SnapshotScopePolicy = AgentDeviceSnapshotPresentation.SnapshotScopePolicy
typealias SnapshotScopeSelection = AgentDeviceSnapshotPresentation.SnapshotScopeSelection
typealias SnapshotPresentationFailure = AgentDeviceSnapshotPresentation.SnapshotPresentationFailure
typealias PresentationOptions = AgentDeviceSnapshotPresentation.PresentationOptions
typealias PresentedNode = AgentDeviceSnapshotPresentation.PresentedNode
typealias SnapshotCustomActionCoverage = AgentDeviceSnapshotPresentation.SnapshotCustomActionCoverage
